#!/bin/bash
dotvim_dir=$(cd "$(dirname "$0")" && pwd)

if [ $dotvim_dir -ef ~/.vim ]; then
	echo ".vim already symlinked or is the actual dotvim repository"
else
	[ -e ~/.vim ] && rm ~/.vim
	ln -s ${dotvim_dir} ~/.vim
fi

[ -e ~/.vimrc ] && rm ~/.vimrc
[ -e ~/.gvimrc ] && rm ~/.gvimrc
ln -s .vim/vimrc ~/.vimrc
ln -s .vim/gvimrc ~/.gvimrc

# make dirs for backups and swaps or vim will give you errors when opening and saving
mkdir ~/.vim/backups
mkdir ~/.vim/swaps

# move backup old jshint/jscs rcs and symlink new ones
[ -e ~/.jshintrc ] && mv ~/.jshintrc ~/.jshintrc.bkup
[ -e ~/.jscsrc ] && mv ~/.jscsrc ~/.jscsrc.bkup
ln -s .jshintrc ~/.jshintrc
ln -s .jscsrc ~/.jscsrc
